name: youtube-sentiment-analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.0
  - pip=25.1 
  - pip:
    - pandas==2.3.0
    - numpy==2.3.0
    - matplotlib==3.10.3
    - streamlit==1.46.0
    - plotly==6.1.2
    - requests==2.32.4
    - urllib3==2.5.0
    - python-dotenv==1.1.0
    - transformers==4.52.4
    - tokenizers==0.21.1
    - huggingface_hub==0.33.0
    - google-api-python-client==2.172.0
    - emoji==2.14.1
    - wordcloud==1.9.4
    - vaderSentiment==3.3.2
    - torch --index-url https://download.pytorch.org/whl/cu126
    - torchvision --index-url https://download.pytorch.org/whl/cu126
    - torchaudio --index-url https://download.pytorch.org/whl/cu126